default: &default
  adapter: mysql2
  database: magic_box
  username: root
  password: Root@123!
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default